Ajustes na tela `Home`
EscolaDeSaudePublica/qualiquiz pull request #71
Opened 2021-09-16 19:13 UTC by ericsonmoreira

# Ajustes na tela `Home`

## Responsáveis

@ericsonmoreira 

## Linked Issue

Close #64

## 📝 Descrição

Durante o desenvolvimento, parecia fazer sentido colocar uma propriedade `css` que mostra um reticencias (...) no título de um Card de Avaliação. Mas isso gera um problema na visualização completa do nome do `quiz`.

- Ajuste no título do card de avaliação. Não faz muito sentido usar o o ... no título dos cards de avaliação.

## 🖥 Passos a passo para teste

Descrever_o_passo_a_passo_para_testar_o_pr

1. Acessar uma página de card de avaliação
2. Mudar o título para verificar como sele se comporta
3. Verificar se ele está obedecendo os critérios de aceite

## 📋 Checklist para criação do PR

- [ ] Testes foram implementados (novos ou não)
- [x] Issue foi definida no PR (Linked Issue na coluna à direita da página)
- [x] Pessoas contribuidoras foram definidas no PR (Assigners no PR)

2021-09-17 11:58 UTC, Laysacunha requested changes
Na tela home, o card de valiações disponíveis deve ter largura fixa (entre 155 e 200px) como combinado durante o deskcheck.
O texto deve se ajustar à segunda linha quando o tamanho ultrapassar a largura definida.
Caso o texto ultrapasse duas linhas, o corte com ... deve ser realizado.

Lembrando que na tela de todas as avaliações esse comportamento não é necessário. o card de avaliações disponíveis e concluídas se comportam da mesma forma.

As imagens abaixo mostram como a largura não está fixa.

![image](https://user-images.githubusercontent.com/20958122/133778911-20a8ebe4-1e13-4258-a12d-1fbf9dfb1ea8.png)
![image](https://user-images.githubusercontent.com/20958122/133778973-b19c049d-ac80-4f55-9763-9d9563bc0809.png)

2021-09-17 18:28 UTC, ericsonmoreira commented
Coloquei o `wrapper` que encapsula o Card de avaliação com tamanho fixo de `220px`.

2021-09-17 18:51 UTC, ericsonmoreira commented
Para testar, podemos usar isso no `Welcome.vue`:

```js
// Lá em export default
data () {
  return {
    notContentMesage: '',
    quizzesTeste: [
      {
        id: 1,
        titulo: 'Manejo ',
        acertos: 5,
        respondido: false,
        data_criacao: new Date()
      },
      {
        id: 2,
        titulo: 'Manejo clínico de paciente com Covid-19',
        acertos: 5,
        respondido: false,
        data_criacao: new Date()
      },
      {
        id: 3,
        titulo: 'Manejo clínico de paciente com Covid-19',
        acertos: 5,
        respondido: false,
        data_criacao: new Date()
      },
      {
        id: 4,
        titulo: 'Manejo clínico de paciente com Covid-19',
        acertos: 5,
        respondido: false,
        data_criacao: new Date()
      }
    ]
  }
},

// Lá no template
<ListingCardsHorizontal
  :data="quizzesTeste"
  notContentMesage="Você ainda não possui novas avaliações.
  Aguarde que logo estará disponível!"
/>
```

2021-09-23 14:05 UTC, Laysacunha approved these changes

2021-09-23 16:43 UTC, merged